ga check publish

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,10 +36,20 @@ jobs:
           export PUBLISH_CHECK_STATUS=$(dart ./script/tool/lib/src/main.dart read-map-json --json "$PUBLISH_CHECK_JSON" --key "status")
           echo "The PUBLISH_CHECK_STATUS is: " + $PUBLISH_CHECK_STATUS
         working-directory: ${{ github.workspace }}/plugins
-      - name: Cancel if published
-        # Prints the status, all the steps after this only runs if PUBLISH_CHECK_STATUS != 'published'
+      - name: Cancel if PUBLISH_CHECK_STATUS no-publish
+        # Prints the status, all the steps after this only runs if PUBLISH_CHECK_STATUS == 'needs-publish'
         run: echo "The plugins updated in this commit have already been published."
-        if: ${{ PUBLISH_CHECK_STATUS == 'published' }}
+        if: ${{ PUBLISH_CHECK_STATUS == 'no-publish' }}
+      - name: Report failure if PUBLISH_CHECK_STATUS error
+        # Prints the status, all the steps after this only runs if PUBLISH_CHECK_STATUS == 'needs-publish'
+        run: |
+          echo "There's an error occured in `publish-check`, please find the details in the "Get publish check status" step"
+          exit 1
+        if: ${{ PUBLISH_CHECK_STATUS == 'error' }}
+
+# ######################################################################################### #
+# All the steps below must be run with `if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}` #
+# ######################################################################################### #
 
       # This workflow should be the last to run. So wait for all the other tests to succeed.
       - name: Wait on all tests
@@ -50,7 +60,7 @@ jobs:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           wait-interval: 10 # seconds
           allowed-conclusions: success
-        if: ${{ PUBLISH_CHECK_STATUS != 'published' }}
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
 
       # The release process should be synchronized to avoid child commit release before the parent commit,
       # which might cause issue when child commit and parent commit both contain version updates for the same
@@ -65,19 +75,19 @@ jobs:
           # TODO(cyanglaz), only allow success and skipped after https://github.com/flutter/plugins/pull/3840 lands and correct configurations added to this workflow.
           # https://github.com/flutter/flutter/issues/81444
           allowed-conclusions: success,skipped,cancelled,failure
-        if: ${{ PUBLISH_CHECK_STATUS != 'published' }}
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
 
       # Checks out a copy of the repo.
       - name: Checkout code
         uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
         with:
           fetch-depth: 0 # Fetch all history so the tool can get all the tag to determine version.
-        if: ${{ PUBLISH_CHECK_STATUS != 'published' }}
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
 
       # TODO(cyanglaz): add real publish command.
       - name: run release
         run: echo "replace this command with release command"
-        if: ${{ PUBLISH_CHECK_STATUS != 'published' }}
+        if: ${{ PUBLISH_CHECK_STATUS == 'needs-publish' }}
 
         env:
           DEFAULT_BRANCH: master
